### PR TITLE
Update Ruler.php

### PR DESCRIPTION
**Pull request by simkimsia**
add in alias because interprete is the wrong English spelling

### CODE REVIEW

**Comment by stephpy** [comment]
:+1:  Thank you.

@Hywan may be we could add a tag on `interprete` method with `@deprecreated will be removed on 2.x` ?

When we'll have a substantial feature/BC break to introduce, we should not support alias IMO.
Since we introduce versioning, we are able to do theses BC break when upgrading `X`. :)

**Comment by Hywan** [comment]
@stephpy Why not. :+1:

**Comment by Savageman** [comment]
Maybe we also should make the deprecated `interprete()` method call the correct `interpret()` method? Right now, we added  the correct spelling as an alias, but I feel it's more logical to do it the other way.

**Comment by Jir4** [comment]
@Savageman +1

**Comment by Hywan** [comment]
@Savageman +1. Please @simkimsia, could you update this PR accordingly to what @Savageman said? Thanks!

**Comment by Hywan** [comment]
Welcome https://github.com/hoaproject/Central/commit/d73b466643465b164c83a034b7b7e934701934e8!

**Comment by Hywan** [comment]
And here: http://hoa-project.net/Community.html#Contributors.

**Comment by Hywan** [comment]
I applied reviews of @stephpy and @Savageman here: https://github.com/hoaproject/Ruler/commit/e61fbb8a59f4b06059911c14aebe295e06e5ab23.

**Comment by Hywan** [comment]
A new snapshot has been released: `1.15.02.02`.

**Comment by simkimsia** [comment]
Oops sorry I didn't get the email alert for this. Thank you @Bhoat for merging this

**Comment by stephpy** [comment]
:+1:

**Pull request merged**
