### PR TITLE
Added \ArrayAccess support for context array dimension access

### PR DESCRIPTION
**Pull request by arnegroskurth**
Gives greater flexibility for context data

### CODE REVIEW

**Comment by Hywan** [comment]
Hello 🙂,

Thanks for the PR! Can you update the test suites too please?

**Comment by Hywan** [comment]
If you don't have time to update the test suites, ask us to do it. Thanks!

**Comment by arnegroskurth** [comment]
Hey there! Sorry for my late reply. I would really appreciate if you could write a suitable test suite. Thanks!

**Comment by Hywan** [comment]
Thanks! See https://github.com/hoaproject/Ruler/commit/9907ffff9ab2074042ab76aee4ba102d3c499ca6 for the commit about tests.

**Comment by manuelbcd** [comment]
+1 Thanks

**Pull request merged**
