### PR TITLE
Allow an identifier to start by a digit

### PR DESCRIPTION
**Pull request by Hywan**
Fix https://github.com/hoaproject/Ruler/issues/32.

Guys, the regex is overly complicated. I am still not a big fan of this feature :-(. Do you think it is really needed?

### CODE REVIEW

**Comment by shouze** [comment]
@Hywan I'm not a fan too... have your compared the match cost with Hoa\Bench? :)

**Comment by Hywan** [comment]
@shouze Is it important to compare performances? Without any doubt, this new regex will be slower, and hard to test if there is no regression :-/.

**Comment by gael-wogenstahl** [comment]
Isn't it faster to change the digit regular expression ?

**Comment by Hywan** [comment]
@gael-wogenstahl Good question, and I don't think so by experience.

Also, I was thinking: If we introduce a scientific notation for numbers (1.2e+4, or… 1e for example), it will conflict with this PR.

So, a new :-1: for me :-/. What do you think @shouze, @stephpy, @osaris, @gael-wogenstahl, @vonglasow? (I pinged all people in #32).

**Comment by shouze** [comment]
@Hywan yes good catch. In definitive which good reason should conduct to allow var name / identifier to start with a digit?

... Except if we introduce a new special notation for identifiers that help to match them more precisely like in a template engine (think about mustache notation for example). This new kind of notation would be a potential BC break feature but yes, in this case we can imagine identifiers that start with a digit.

ping @stephpy @Hywan @osaris @gael-wogenstahl @vonglasow?

**Comment by stephpy** [comment]
Why an identifier would use a scientific notation ? It's not question about computing the identifier key, it should be static. 1e should look at $context['1e'].

But once again, it's not a big feature add to support it ... we could not support it and users will have to begin by a letter.

**Comment by Hywan** [comment]
@stephpy I meant if we write `1e` it can an identifier **or** a number (if we introduce the scientific notation), so we will have a conflict. For me, having scientific notation is more important than having variable starting by a digit :-/.

Thoughts?

**Comment by vonglasow** [comment]
For me it's not really needed. It could be helpful for whose need it but as I know it's not a real good practice. @Hywan +1

**Comment by stephpy** [comment]
@Hywan +1

**Pull request closed without merging**
