### PR TITLE
Disassembly: Always add parenthesis around operators

### LINKED ISSUE #79: Incorrect condition on disassembly
Hi all,

There is a problem in [Disassembly class](https://github.com/hoaproject/Ruler/blob/master/Visitor/Disassembly.php#L83) on the isToken condition.
Instead of adding parenthesis when using not, and, or, xor , it adds parenthesis on other operators.
Example:
- the rule I write and I expect to get after interpreting it, getting the Model and then disassembling it:
```
((age > 50 and civility = 'mr') or (age < 40 and civility = 'mrs'))
```
- the rule I currently get with hoa/ruler in version 1.15.11.09 :
```
(age > 50) and (civility = 'mr') or (age < 40) and (civility = 'mrs')
```

I guess that the isToken condition , instead of being compared to false, should be compared to true.
Modifying this condition this way, I get the expected result.

Thanks in advance :-)

### PR DESCRIPTION
**Pull request by Hywan**
Fix #79.
Fix #80.

Thoughts @stephpy, @Metalaka, @osaris and @shouze.

### CODE REVIEW

**Comment by osaris** [comment]
Hi @Hywan I'd like to test your PR locally but when I ```composer install``` I have the following errors :

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - atoum/praspel-extension 0.16.01.11 requires hoa/math ~0.0 -> satisfiable by hoa/math[0.14.09.16, 0.14.09.17, 0.14.09.23, 0.14.11.09, 0.14.12.10, 0.14.12.22, 0.15.02.23, 0.15.05.29, 0.15.08.25, 0.15.10.26].
    - hoa/test 2.16.01.11 requires hoa/file ~0.0 -> no matching package found.
    - hoa/math 0.15.10.26 requires hoa/compiler ~2.0 -> no matching package found.
    - hoa/math 0.15.08.25 requires hoa/compiler ~2.0 -> no matching package found.
    - hoa/math 0.15.05.29 requires hoa/compiler ~2.0 -> no matching package found.
    - hoa/math 0.15.02.23 requires hoa/compiler ~2.0 -> no matching package found.
    - hoa/math 0.14.12.22 requires hoa/compiler ~2.0 -> no matching package found.
    - hoa/math 0.14.12.10 requires hoa/compiler ~2.0 -> no matching package found.
    - hoa/math 0.14.11.09 requires hoa/compiler ~2.0 -> no matching package found.
    - hoa/math 0.14.09.23 requires hoa/compiler ~2.0 -> no matching package found.
    - hoa/math 0.14.09.17 requires hoa/compiler ~2.0 -> no matching package found.
    - hoa/math 0.14.09.16 requires hoa/compiler ~1.0 -> no matching package found.
    - hoa/test 2.16.01.14 requires atoum/praspel-extension ~0.16 -> satisfiable by atoum/praspel-extension[0.16.01.11].
    - Installation request for hoa/test ~2.0 -> satisfiable by hoa/test[2.16.01.11, 2.16.01.14].
```

**Comment by Metalaka** [comment]
@osaris `composer install` works with me, but I didn't test this PR changes…
```sh
$ composer require hoa/ruler

Using version 2.16.01.15 for hoa/ruler
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing hoa/exception (1.16.01.11)
    Downloading: 100%

  - Installing hoa/consistency (1.16.01.14)
    Downloading: 100%

  - Installing hoa/event (1.16.01.11)
    Downloading: 100%

  - Installing hoa/visitor (2.16.01.11)
    Downloading: 100%

  - Installing hoa/iterator (2.16.01.11)
    Downloading: 100%

  - Installing hoa/protocol (1.16.01.11)
    Downloading: 100%

  - Installing hoa/stream (1.16.01.14)
    Downloading: 100%

  - Installing hoa/file (1.16.01.15)
    Downloading: 100%

  - Installing hoa/ustring (4.16.01.11)
    Downloading: 100%

  - Installing hoa/zformat (1.16.01.14)
    Downloading: 100%

  - Installing hoa/compiler (3.16.01.14)
    Downloading: 100%

  - Installing hoa/math (1.16.01.15)
    Downloading: 100%

  - Installing hoa/regex (1.16.01.15)
    Downloading: 100%

  - Installing hoa/ruler (2.16.01.15)
    Downloading: 100%

Writing lock file
Generating autoload files
```

**Comment by osaris** [comment]
Installing with ```--no-dev``` is ok.

**Comment by osaris** [comment]
I confirm that this PR fix the bug in #79
I can't run tests for the moment (see my previous comment).

Do we need a test case for this ?

**Comment by Hywan** [comment]
We can't install `hoa/test` because of an atoum extension. PLease, see https://github.com/atoum/ruler-extension/pull/29 and https://github.com/atoum/ruler-extension/pull/30.

**Comment by Hywan** [comment]
@osaris Yup, should be great to add a test case…

**Comment by jubianchi** [comment]
everything should be ready for you to fix this issue. See:

* https://github.com/atoum/ruler-extension/releases/tag/1.2.0
* https://packagist.org/packages/atoum/ruler-extension#1.2.0

It was a long journey, but we made it ;)

**Comment by Hywan** [comment]
`Hoa\Test` has been fixed. New snapshot deployed.

**Comment by Hywan** [comment]
ping @osaris?

**Comment by julban** [comment]
Hi @Hywan and @osaris , is there anything missing to get this PR merged?
Thx

**Comment by Hywan** [comment]
@julban I don't think so. @osaris needs to review it before the merge.

**Comment by osaris** [comment]
@julban thanks for the reminder. Tests are green, code looks good to me. We miss a test for this bug to avoid regression, do we write it before we merge (ping @Hywan) ?

**Comment by Hywan** [comment]
@osaris Yup, we should. This issue https://github.com/hoaproject/Regex/issues/14 is blocking in order to get automatic test data generation unfortunately… but I think we will write manual tests before merging this patch. I don't want to introduce any regressions.

**Comment by Hywan** [comment]
@osaris Tests have been added. Solving the issue with `Hoa\Regex` is too hard for now. Ready to be merged.

**Pull request merged**
